### ISSUE TITLE
S3 copy claims "Source does not exist" if it does not have destination permission

### ISSUE THREAD

**Issue by btparker** [bodylabs/baiji#31]
To recreate:

`mkdir foo/`
`s3 cp s3://bucket/bar.txt foo/`

Copies just fine.

`chmod 666 foo/`
`s3 cp s3://bucket/bar.txt foo/`

Error says:
`baiji.exceptions.KeyNotFound: Error copying s3://bucket/bar.txt to /Users/user/foo/bar.txt: Source doesn't exist`

**Comment by algrs** [comment]
Resolved by #33 / version 2.5.3
